// =============================================================================
// RSemble AI — Run record builder tests
//
// Verifies the pure functions that convert executor events into RunRecordV2
// mutations and derive FullRunSummaryV2. No I/O, no side effects.
// Status derivation follows spec §7.5.
// =============================================================================

import { describe, it, expect } from "vitest";
import type { ChatMessage } from "../providers/types";
import type { JudgeReport, ConsensusBreakdown, CandidateEvaluation } from "../../studio-data";
import type { RunSource, ExecutionFence } from "./run-types";
import {
  createRunRecordBuilder,
  type RunRecordBuilderState,
  type BuilderDeps,
} from "./run-record-builder";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const FENCE: ExecutionFence = { ownerId: "tab-1", fence: 1 };
const ADHOC: RunSource = { kind: "adhoc" };

const TWO_SLOTS = [
  { id: "s1", providerId: "openrouter", model: "A", slug: "model-a", enabled: true },
  { id: "s2", providerId: "umans", model: "B", slug: "model-b", enabled: true },
] as const;

function makeDeps(): BuilderDeps {
  let counter = 0;
  return {
    generateId: () => `id-${++counter}`,
    now: () => 1000,
  };
}

function makeMessages(): ChatMessage[] {
  return [
    { role: "system", content: "system prompt" },
    { role: "user", content: "test prompt" },
  ];
}

function makeConsensus(): ConsensusBreakdown {
  return { consensus: ["A is better"], contradictions: [], uniqueInsights: [] };
}

function makeJudgeReport(scoresById: Record<string, number>): JudgeReport {
  const labelMap = Object.keys(scoresById).map((candidateId, i) => ({
    label: String.fromCharCode(65 + i),
    candidateId,
  }));
  const evaluationsById: Record<string, CandidateEvaluation> = {};
  for (const { label, candidateId } of labelMap) {
    evaluationsById[candidateId] = {
      candidateId,
      blindLabel: label,
      overallScore: scoresById[candidateId],
      position: `Position ${label}`,
      rationale: `Evidence ${label}`,
      strengths: [`Strength ${label}`],
      deductions: [],
      missedRequirements: [],
      criterionScores: [],
    };
  }
  return { labelMap, evaluationsById, comparisons: [] };
}

function startFanout(state: RunRecordBuilderState, builder: ReturnType<typeof createRunRecordBuilder>, slots = TWO_SLOTS) {
  return builder.applyFanoutStart(state, {
    runId: "run-1",
    source: ADHOC,
    mode: "rank" as const,
    task: { title: "Test Task", prompt: "test prompt", systemPrompt: "system prompt", temperature: 0.7 },
    evaluation: { profile: null, candidateMessages: [] },
    slots: slots.map((s) => ({ ...s, provider: "P" })),
    fence: FENCE,
  });
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe("RunRecordBuilder — fanout start", () => {
  it("creates one stable run ID plus one running candidate attempt per enabled slot", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);

    expect(record.id).toBe("run-1");
    expect(record.status).toBe("running");
    expect(record.candidates).toHaveLength(2);
    for (const c of record.candidates) {
      expect(c.attempts).toHaveLength(1);
      expect(c.attempts[0].status).toBe("running");
      expect(c.attempts[0].startedAt).toBe(1000);
      expect(c.attempts[0].finishedAt).toBeNull();
    }
  });

  it("assigns immutable candidateId, slotId, modelKey per candidate", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);

    expect(record.candidates[0].candidateId).toBe("s1");
    expect(record.candidates[0].slotId).toBe("s1");
    expect(record.candidates[0].modelKey).toBe("openrouter:model-a");
    expect(record.candidates[1].candidateId).toBe("s2");
    expect(record.candidates[1].modelKey).toBe("umans:model-b");
  });
});

describe("RunRecordBuilder — IdFactory", () => {
  it("generates IDs through deps.generateId; persistence never invents identity", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    // Candidate attempt IDs are generated by the builder, not persistence
    expect(record.candidates[0].attempts[0].attemptId).toBeTruthy();
    expect(record.candidates[0].attempts[0].attemptId).not.toBe(record.candidates[1].attempts[0].attemptId);
  });
});

describe("RunRecordBuilder — candidate terminal", () => {
  it("stores segments, output, tokens, timings on terminal", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    const candidateId = "s1";
    const attemptId = record.candidates[0].attempts[0].attemptId;

    builder.applyCandidateAttemptTerminal(state, record, candidateId, attemptId, {
      status: "completed",
      output: "answer text",
      tokensIn: 10,
      tokensOut: 20,
      error: null,
      finishedAt: 2000,
    });

    const attempt = record.candidates[0].attempts[0];
    expect(attempt.status).toBe("completed");
    expect(attempt.output).toBe("answer text");
    expect(attempt.tokensIn).toBe(10);
    expect(attempt.tokensOut).toBe(20);
    expect(attempt.finishedAt).toBe(2000);
  });

  it("stores bounded sanitized error on failure", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);

    builder.applyCandidateAttemptTerminal(state, record, "s1", record.candidates[0].attempts[0].attemptId, {
      status: "failed",
      output: null,
      tokensIn: null,
      tokensOut: null,
      error: { message: "connection reset" },
      finishedAt: 2000,
    });

    expect(record.candidates[0].attempts[0].status).toBe("failed");
    expect(record.candidates[0].attempts[0].error).toEqual({ message: "connection reset" });
  });
});

describe("RunRecordBuilder — candidate retry", () => {
  it("appends a running attempt before the call", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    // Finalize the first attempt
    builder.applyCandidateAttemptTerminal(state, record, "s1", record.candidates[0].attempts[0].attemptId, {
      status: "completed", output: "first", tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
    });

    // Retry: append a new running attempt
    builder.applyCandidateAttemptStart(state, record, "s1", {
      attemptId: "retry-att-1",
      messages: makeMessages(),
      startedAt: 3000,
    });

    expect(record.candidates[0].attempts).toHaveLength(2);
    expect(record.candidates[0].attempts[1].status).toBe("running");
    expect(record.candidates[0].attempts[1].attemptId).toBe("retry-att-1");
  });

  it("success moves accepted pointer; failure preserves prior accepted output", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    const firstAttemptId = record.candidates[0].attempts[0].attemptId;
    builder.applyCandidateAttemptTerminal(state, record, "s1", firstAttemptId, {
      status: "completed", output: "first", tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
    });

    // Retry attempt
    builder.applyCandidateAttemptStart(state, record, "s1", {
      attemptId: "retry-att-1", messages: makeMessages(), startedAt: 3000,
    });
    builder.applyCandidateAttemptTerminal(state, record, "s1", "retry-att-1", {
      status: "completed", output: "second", tokensIn: 6, tokensOut: 12, error: null, finishedAt: 4000,
    });
    expect(record.candidates[0].acceptedAttemptId).toBe("retry-att-1");

    // Another retry that fails — should NOT move accepted pointer
    builder.applyCandidateAttemptStart(state, record, "s1", {
      attemptId: "retry-att-2", messages: makeMessages(), startedAt: 5000,
    });
    builder.applyCandidateAttemptTerminal(state, record, "s1", "retry-att-2", {
      status: "failed", output: null, tokensIn: null, tokensOut: null,
      error: { message: "failed" }, finishedAt: 6000,
    });
    expect(record.candidates[0].acceptedAttemptId).toBe("retry-att-1");
    expect(record.candidates[0].attempts).toHaveLength(3);
  });
});

describe("RunRecordBuilder — Judge", () => {
  function setupJudgeReady() {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    for (const c of record.candidates) {
      builder.applyCandidateAttemptTerminal(state, record, c.candidateId, c.attempts[0].attemptId, {
        status: "completed", output: `answer-${c.candidateId}`, tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
      });
    }
    return { builder, state, record };
  }

  it("starts as running with immutable attempt ID, messages, blind map, candidate refs", () => {
    const { builder, state, record } = setupJudgeReady();
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "be strict",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 3000,
    });
    const j = record.judge;
    expect(j.status).toBe("running");
    expect(j.attempts).toHaveLength(1);
    expect(j.attempts[0].attemptId).toBe("judge-att-1");
    expect(j.attempts[0].messages).toHaveLength(2);
    expect(j.attempts[0].blindLabelToCandidateId).toEqual({ A: "s1", B: "s2" });
    expect(j.attempts[0].candidateAttemptIdsByCandidateId).toEqual({ s1: "att-1", s2: "att-2" });
  });

  it("success retains report, consensus, scores, and accepted pointer", () => {
    const { builder, state, record } = setupJudgeReady();
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 3000,
    });
    const report = makeJudgeReport({ s1: 4, s2: 3 });
    const consensus = makeConsensus();
    builder.applyJudgeTerminal(state, record, "judge-att-1", {
      status: "completed", report, consensus, error: null, finishedAt: 4000,
    });
    expect(record.judge.status).toBe("done");
    expect(record.judge.acceptedAttemptId).toBe("judge-att-1");
    expect(record.judge.report).toBe(report);
    expect(record.judge.consensus).toBe(consensus);
  });

  it("candidate retry failure preserves prior accepted Judge and candidate refs", () => {
    const { builder, state, record } = setupJudgeReady();
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 3000,
    });
    const report = makeJudgeReport({ s1: 4, s2: 3 });
    builder.applyJudgeTerminal(state, record, "judge-att-1", {
      status: "completed", report, consensus: null, error: null, finishedAt: 4000,
    });

    // New Judge attempt after candidate retry — fails
    builder.applyJudgeStart(state, record, "judge-att-2", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "retry-att-1", s2: "att-2" },
      startedAt: 5000,
    });
    builder.applyJudgeTerminal(state, record, "judge-att-2", {
      status: "failed", report: null, consensus: null,
      error: { message: "malformed" }, finishedAt: 6000,
    });

    // Prior accepted Judge preserved
    expect(record.judge.acceptedAttemptId).toBe("judge-att-1");
    expect(record.judge.report).toBe(report);
    expect(record.judge.attempts).toHaveLength(2);
  });
});

describe("RunRecordBuilder — Fusion", () => {
  function setupFusionReady() {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    for (const c of record.candidates) {
      builder.applyCandidateAttemptTerminal(state, record, c.candidateId, c.attempts[0].attemptId, {
        status: "completed", output: `answer-${c.candidateId}`, tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
      });
    }
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 3000,
    });
    builder.applyJudgeTerminal(state, record, "judge-att-1", {
      status: "completed", report: makeJudgeReport({ s1: 4, s2: 3 }),
      consensus: null, error: null, finishedAt: 4000,
    });
    return { builder, state, record };
  }

  it("appends running fusion with source Judge and candidate attempt IDs", () => {
    const { builder, state, record } = setupFusionReady();
    builder.applyFusionStart(state, record, "fusion-att-1", {
      providerId: "openrouter", model: "judge-model",
      messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 5000,
    });
    expect(record.fusion.status).toBe("running");
    expect(record.fusion.attempts).toHaveLength(1);
    expect(record.fusion.attempts[0].sourceJudgeAttemptId).toBe("judge-att-1");
  });

  it("success moves accepted pointer; failed re-fuse preserves prior accepted", () => {
    const { builder, state, record } = setupFusionReady();
    builder.applyFusionStart(state, record, "fusion-att-1", {
      providerId: "openrouter", model: "judge-model",
      messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 5000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-1", {
      status: "completed", result: "fused text", error: null, finishedAt: 6000,
    });
    expect(record.fusion.acceptedAttemptId).toBe("fusion-att-1");

    // Re-fuse that fails
    builder.applyFusionStart(state, record, "fusion-att-2", {
      providerId: "openrouter", model: "judge-model",
      messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "att-1", s2: "att-2" },
      startedAt: 7000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-2", {
      status: "failed", result: null, error: { message: "fusion failed" }, finishedAt: 8000,
    });
    // Prior accepted Fusion preserved
    expect(record.fusion.acceptedAttemptId).toBe("fusion-att-1");
    expect(record.fusion.attempts).toHaveLength(2);
  });
});

describe("RunRecordBuilder — summary derivation", () => {
  it("search text contains task title/excerpt and model IDs", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    const summary = builder.deriveSummary(record);
    expect(summary.searchText).toContain("Test Task");
    expect(summary.searchText).toContain("test prompt");
    expect(summary.searchText).toContain("model-a");
    expect(summary.searchText).toContain("model-b");
  });

  it("summary has detailAvailable: true, kind: full, schemaVersion: 2", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    const summary = builder.deriveSummary(record);
    expect(summary.kind).toBe("full");
    expect(summary.schemaVersion).toBe(2);
    expect(summary.detailAvailable).toBe(true);
    expect(summary.modelKeys).toEqual(["openrouter:model-a", "umans:model-b"]);
  });
});

describe("RunRecordBuilder — status derivation (§7.5)", () => {
  function setup(mode: "rank" | "fuse" = "rank") {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = builder.applyFanoutStart(state, {
      runId: "run-1", source: ADHOC, mode,
      task: { title: "T", prompt: "p", systemPrompt: "", temperature: 0.7 },
      evaluation: { profile: null, candidateMessages: [] },
      slots: TWO_SLOTS.map((s) => ({ ...s, provider: "P" })),
      fence: FENCE,
    });
    return { builder, state, record };
  }

  function completeAllCandidates(builder: ReturnType<typeof createRunRecordBuilder>, state: RunRecordBuilderState, record: ReturnType<ReturnType<typeof createRunRecordBuilder>["applyFanoutStart"]>) {
    for (const c of record.candidates) {
      builder.applyCandidateAttemptTerminal(state, record, c.candidateId, c.attempts[0].attemptId, {
        status: "completed", output: `out-${c.candidateId}`, tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
      });
    }
  }

  function runJudge(builder: ReturnType<typeof createRunRecordBuilder>, state: RunRecordBuilderState, record: ReturnType<ReturnType<typeof createRunRecordBuilder>["applyFanoutStart"]>, ok: boolean) {
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: record.candidates[0].attempts[0].attemptId, s2: record.candidates[1].attempts[0].attemptId },
      startedAt: 3000,
    });
    builder.applyJudgeTerminal(state, record, "judge-att-1", ok
      ? { status: "completed", report: makeJudgeReport({ s1: 4, s2: 3 }), consensus: null, error: null, finishedAt: 4000 }
      : { status: "failed", report: null, consensus: null, error: { message: "bad" }, finishedAt: 4000 });
  }

  it("running: provider calls active, no terminal action", () => {
    const { builder, state, record } = setup();
    builder.applyFanoutTerminal(state, record, []);
    expect(builder.deriveStatus(record)).toBe("running");
  });

  it("completed: accepted Judge + all candidates usable, no Fusion requested", () => {
    const { builder, state, record } = setup("rank");
    completeAllCandidates(builder, state, record);
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, true);
    expect(builder.deriveStatus(record)).toBe("completed");
  });

  it("completed: accepted Judge + all candidates + accepted Fusion in fuse mode", () => {
    const { builder, state, record } = setup("fuse");
    completeAllCandidates(builder, state, record);
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, true);
    builder.applyFusionStart(state, record, "fusion-att-1", {
      providerId: "openrouter", model: "judge-model", messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "a1", s2: "a2" }, startedAt: 5000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-1", {
      status: "completed", result: "fused", error: null, finishedAt: 6000,
    });
    expect(builder.deriveStatus(record)).toBe("completed");
  });

  it("partial: accepted Judge with one failed candidate", () => {
    const { builder, state, record } = setup("rank");
    // First candidate completes
    builder.applyCandidateAttemptTerminal(state, record, "s1", record.candidates[0].attempts[0].attemptId, {
      status: "completed", output: "out-s1", tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
    });
    // Second candidate fails
    builder.applyCandidateAttemptTerminal(state, record, "s2", record.candidates[1].attempts[0].attemptId, {
      status: "failed", output: null, tokensIn: null, tokensOut: null, error: { message: "fail" }, finishedAt: 2000,
    });
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, true);
    expect(builder.deriveStatus(record)).toBe("partial");
  });

  it("partial: accepted Judge but requested Fusion has no accepted result", () => {
    const { builder, state, record } = setup("fuse");
    completeAllCandidates(builder, state, record);
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, true);
    // Fusion started but failed
    builder.applyFusionStart(state, record, "fusion-att-1", {
      providerId: "openrouter", model: "judge-model", messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "a1", s2: "a2" }, startedAt: 5000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-1", {
      status: "failed", result: null, error: { message: "fusion fail" }, finishedAt: 6000,
    });
    expect(builder.deriveStatus(record)).toBe("partial");
  });

  it("failed: fewer than two usable candidates", () => {
    const { builder, state, record } = setup("rank");
    // Both fail
    for (const c of record.candidates) {
      builder.applyCandidateAttemptTerminal(state, record, c.candidateId, c.attempts[0].attemptId, {
        status: "failed", output: null, tokensIn: null, tokensOut: null, error: { message: "fail" }, finishedAt: 2000,
      });
    }
    builder.applyFanoutTerminal(state, record, []);
    expect(builder.deriveStatus(record)).toBe("failed");
  });

  it("failed: Judge ends without accepted report", () => {
    const { builder, state, record } = setup("rank");
    completeAllCandidates(builder, state, record);
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, false);
    expect(builder.deriveStatus(record)).toBe("failed");
  });

  it("aborted: user abort wins", () => {
    const { builder, state, record } = setup();
    builder.applyAborted(state, record);
    expect(record.status).toBe("aborted");
    expect(builder.deriveStatus(record)).toBe("aborted");
  });

  it("interrupted: startup recovery finds expired lease", () => {
    const { builder, state, record } = setup();
    builder.applyInterrupted(state, record);
    expect(record.status).toBe("interrupted");
    expect(builder.deriveStatus(record)).toBe("interrupted");
  });

  it("failed re-fuse with prior accepted Fusion preserves completed/partial", () => {
    const { builder, state, record } = setup("fuse");
    completeAllCandidates(builder, state, record);
    builder.applyFanoutTerminal(state, record, []);
    runJudge(builder, state, record, true);
    // First fusion succeeds
    builder.applyFusionStart(state, record, "fusion-att-1", {
      providerId: "openrouter", model: "judge-model", messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "a1", s2: "a2" }, startedAt: 5000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-1", {
      status: "completed", result: "fused", error: null, finishedAt: 6000,
    });
    // Re-fuse fails
    builder.applyFusionStart(state, record, "fusion-att-2", {
      providerId: "openrouter", model: "judge-model", messages: makeMessages(),
      sourceJudgeAttemptId: "judge-att-1",
      candidateAttemptIdsByCandidateId: { s1: "a1", s2: "a2" }, startedAt: 7000,
    });
    builder.applyFusionTerminal(state, record, "fusion-att-2", {
      status: "failed", result: null, error: { message: "refuse fail" }, finishedAt: 8000,
    });
    // Still completed because prior accepted Fusion exists
    expect(builder.deriveStatus(record)).toBe("completed");
  });
});

describe("RunRecordBuilder — winners", () => {
  it("equal top scores produce multiple winnerKeys", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    for (const c of record.candidates) {
      builder.applyCandidateAttemptTerminal(state, record, c.candidateId, c.attempts[0].attemptId, {
        status: "completed", output: `out-${c.candidateId}`, tokensIn: 5, tokensOut: 10, error: null, finishedAt: 2000,
      });
    }
    builder.applyFanoutTerminal(state, record, []);
    builder.applyJudgeStart(state, record, "judge-att-1", {
      providerId: "openrouter", model: "judge-model", instruction: "",
      messages: makeMessages(),
      blindLabelToCandidateId: { A: "s1", B: "s2" },
      candidateAttemptIdsByCandidateId: { s1: "a1", s2: "a2" },
      startedAt: 3000,
    });
    // Tie: both score 4
    builder.applyJudgeTerminal(state, record, "judge-att-1", {
      status: "completed",
      report: makeJudgeReport({ s1: 4, s2: 4 }),
      consensus: null, error: null, finishedAt: 4000,
    });
    const summary = builder.deriveSummary(record);
    expect(summary.winnerKeys).toHaveLength(2);
    expect(summary.winnerKeys).toContain("openrouter:model-a");
    expect(summary.winnerKeys).toContain("umans:model-b");
  });
});

describe("RunRecordBuilder — prohibited keys", () => {
  it("no prohibited transport/credential fields are serialized", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state = builder.createInitialState();
    const record = startFanout(state, builder);
    const parsed = JSON.parse(JSON.stringify(record)) as Record<string, unknown>;
    // Check that no credential-like keys exist at any level
    const forbidden = ["apiKey", "authorization", "secret", "password", "token", "bearer"];
    const checkKeys = (obj: unknown, path: string): string[] => {
      if (typeof obj !== "object" || obj === null) return [];
      const found: string[] = [];
      for (const [key, val] of Object.entries(obj)) {
        if (forbidden.includes(key)) found.push(`${path}.${key}`);
        if (typeof val === "object" && val !== null) {
          found.push(...checkKeys(val, `${path}.${key}`));
        }
      }
      return found;
    };
    const violations = checkKeys(parsed, "root");
    expect(violations).toEqual([]);
  });
});

describe("RunRecordBuilder — source metadata", () => {
  it("distinguishes adhoc and experiment task runs", () => {
    const builder = createRunRecordBuilder(makeDeps());
    const state1 = builder.createInitialState();
    const adhocRecord = builder.applyFanoutStart(state1, {
      runId: "r1", source: ADHOC, mode: "rank",
      task: { title: "T", prompt: "p", systemPrompt: "", temperature: 0.7 },
      evaluation: { profile: null, candidateMessages: [] },
      slots: TWO_SLOTS.map((s) => ({ ...s, provider: "P" })),
      fence: FENCE,
    });
    expect(adhocRecord.source).toEqual({ kind: "adhoc" });

    const state2 = builder.createInitialState();
    const expSource: RunSource = {
      kind: "experiment",
      experimentId: "exp-1",
      suiteId: "suite-1",
      suiteVersion: 1,
      protocolFingerprint: "fp-abc",
      taskId: "task-1",
      experimentTaskAttemptId: "exp-att-1",
      trial: 0,
    };
    const expRecord = builder.applyFanoutStart(state2, {
      runId: "r2", source: expSource, mode: "rank",
      task: { title: "T", prompt: "p", systemPrompt: "", temperature: 0.7 },
      evaluation: { profile: null, candidateMessages: [] },
      slots: TWO_SLOTS.map((s) => ({ ...s, provider: "P" })),
      fence: FENCE,
    });
    expect(expRecord.source.kind).toBe("experiment");
    expect(expRecord.source).toEqual(expSource);
  });
});
